services:
  db:
    image: mysql:8.0
    container_name: sms_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2basic
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"

  app:
    image: php:8.2-apache
    container_name: sms_app
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./yii:/var/www/html
    working_dir: /var/www/html
    entrypoint: >
      sh -c "a2enmod rewrite && docker-php-ext-install pdo pdo_mysql && apache2-foreground"
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: sms_pma
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db